# Generated by Django 3.0.5 on 2020-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='contact_info',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centers',
            name='hours',
            field=models.CharField(default='no info', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centers',
            name='routs',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
    ]
