# Generated by Django 3.0.5 on 2020-04-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='center',
            name='fax',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='center',
            name='hours',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='center',
            name='phone',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='center',
            name='routes',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visible', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.City')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.Network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Neighborhood'),
        ),
    ]
