# Generated by Django 3.0.5 on 2020-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
    ]
