# Generated by Django 3.0.5 on 2020-04-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('appointments', '0002_auto_20200429_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center'),
        ),
        migrations.DeleteModel(
            name='Center',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
