# Generated by Django 3.0.5 on 2020-06-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200603_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='center_id',
            new_name='center',
        ),
    ]
