# Generated by Django 3.0.5 on 2020-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='center',
            name='fax',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='center',
            name='hours',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='center',
            name='routes',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
