# Generated by Django 3.0.5 on 2020-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20200504_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='hours',
            field=models.CharField(blank=True, default=None, max_length=800),
        ),
    ]
