# Generated by Django 3.0.5 on 2020-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20200602_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=10, null=True),
        ),
    ]
